### ISSUE TITLE
Colours feature does not seem to be working

### ISSUE THREAD

**Issue by sandhals** [luoliyan/chinese-support-redux#139]
A bit new to using Anki with add-ons so please excuse any ignorance. I wasn't sure where to go for help, but I figured I might have luck here! :) 

I recently installed Chinese Support Redux particularly to enable automatic coloring of my characters for tone in a pre-existing deck. Does Chinese Support Redux only work for decks which you are building yourself? Or can they be applied to pre-existing decks?

The deck I am studying with is this:

https://drive.google.com/file/d/123pXHfElVObijk_6YUwmzMtaqAb9kWmM/view

I have made sure the suggested styling code is applied to the cards, but I still see no colours. Could anyone maybe help me out a bit? Sorry for the ignorant question!!

**Comment by joeminicucci** [comment]
@sandhals 
Your notes must have field names supported by the addon. From the README:
```The core feature of the add-on is the automatic field filling. To take advantage of this, you need to have an Anki note type with the appropriate fields (e.g., Hanzi, English, Pinyin, Sound). See config.json for a list of valid field names.```
You can use any note as long as the field names match since the addon keys off of them. The field names can be found [here](https://github.com/luoliyan/chinese-support-redux/blob/master/chinese/config.json)
or you can see an example by:
```Select Chinese (Basic) or Chinese (Advanced) as the note type```
