### ISSUE TITLE
Anki autofill seems to cause the plugin to crash

### ISSUE THREAD

**Issue by zach7815** [luoliyan/chinese-support-redux#142]
Everytime I try to autofill fields with anything from hanzi to speech pronunciation the plugin seems to crash and report the following error: 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-12 17:46:25
Add-ons possibly involved: ⁨Heatmap, Chinese Support Redux v0140⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Zach/Library/Application Support/Anki2/addons21/1128979221/fill.py", line 374, in bulk_fill_hanzi
    note_ids = Finder(mw.col).findNotes('deck:current')
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-54>", line 2, in __init__
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 630, in repl
  File "/Users/Zach/Library/Application Support/Anki2/addons21/1722241614/links.py", line 149, in addFinders
    self.search["seen"] = self.findSeenOn
AttributeError: 'Finder' object has no attribute 'search'

**Expected behavior**
Auto-fill of fields with hanzi, speech pronunciation etc. 

**Specs (please complete the following information):**
 - OS:  Mac OS Catalina 10.15.5
 - Anki Version: 2.1.26
- Chinese Support Version 0.14

**Additional context**
just updated the version of chinese support today and the error started occurring, I don't know how to revert to the previous version.

**Comment by SpinningCubeSolutions** [comment]
I got the same problem, but only when I tried to use Jyutping instead of Pinyin, or Amazon Polly as a speech source.
Here is the debug info and error message:
`Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-30 21:45:23
Add-ons possibly involved: ⁨Chinese Support Redux v0140⁩`

**Expected behaviour**
Auto fill fields with Jyutping in the "Pinyin" field.
**Specs**
- OS: Catalina 10.15.6
- Anki Version: 2.1.26
- Chinese Support Version: 0.14.0

**Additional info**
Just installed Chinese Support today

**Comment by joeminicucci** [comment]
@zach7815 Can you confirm this problem still exists in the most recent version of the plugin?

@SpinningCubeSolutions  Jyutping currently has known issues and is considered unsupported for the time being

**Comment by zach7815** [comment]
Hi @joeminicucci, 

I no longer face the face the problem in the latest version. It seems to work fine noW for me.
