### ISSUE TITLE
Option to reverse cards

### ISSUE THREAD

**Issue by ksahin** [luoliyan/chinese-support-redux#192]
First of all, thanks for this wonderful addon.

I'd like to create reverse cards: 
- One card with English on the front, and Hanzi/Pinyin + other fields on the back
- One card with Hanzi on the front, and English/Pinyin + other fields on the back

I'm not sure if it's possible right now. 
What I did was to create a new profile, export my current deck, and import it on the new profile. 
Then I changed the template to show the Hanzi field on the front instead of English field. 

This is not a great solution because I have to do this process each time I add new cards to the original deck.

Can someone point me to the right direction? 

Thanks

**Comment by joeminicucci** [comment]
Hi @ksahin, 

This is not a problem with the Chinese Support addon. Card Templates and Note Types should be customizable in Anki, and selectable when adding a new card to a deck. Please see the f[ollowing reference](https://docs.ankiweb.net/templates/intro.html). I will be closing this issue since there is inadequate bug information, as well as the assumption that you are having problems using Anki rather than the addon. The addon operates a layer above card and note templating and plugs in to the fields themselves when filling in the desired Chinese definitions.
