### ISSUE TITLE
German translation truncated

### ISSUE THREAD

**Issue by PandaScience** [luoliyan/chinese-support-redux#58]
**Describe the bug**
When auto-filling the "German" field, the translation is often truncated at strange places. Comparing the behavior of different notes, it could be always the last character in the translated string. Not sure if this is a bug in the addon or if the German dictionary simply is crappy. E.g. in the screenshot, it could be "(Zahl)", where the closing parenthesis is missing. However, "(Zähl" is wrong in any case. May I ask which dictionary is the "built-in" German one? Maybe I can find a better one?

**To Reproduce**
1. Add note with "German" field
2. Insert hanzi in "Hanzi" field
3. Have a look at cut-off German translation

**Expected behavior**
Well, no strange truncations. ;-)

**Screenshots**
![Broken German translation](https://user-images.githubusercontent.com/8038521/55715600-59cd5800-59f5-11e9-84fa-c98ece2e2e62.png)

**Specs (please complete the following information):**
- OS: Arch Linux
- Anki Version 2.1.11 (3cf770c7)
- Chinese Support Version v0.10.0-beta

**Comment by luoliyan** [comment]
Thanks for reporting.

One of the few parts of the add-on I haven't touched is the database creation code. In fact, it doesn't even run under Python 3. The add-on is shipped with a prefabricated database from the previous maintainer, which includes truncated German entries.

I've known this was an issue, but I haven't found the time to address it since it would involve a full rewrite of 360 lines of code I'm not familiar with.

I'll try to give it a light clean-up and get it to run under Python 3, but how far I get will depend on how much time I manage to find.

**Comment by PandaScience** [comment]
Never mind. After adding around 250 entries the last few days I got quite comfortable editing the translations in EN/GER/FR manually. Maybe my judgement about the dictionary's quality has been a bit premature. However, the stuff in parentheses indeed is superfluous - so removing it entirely instead of fixing the missing closing bracket would probably the better way.

Anyways, thank you very much for your work. If I can help somehow, let me know.

**Comment by luoliyan** [comment]
Well it still needs to be fixed, so I'll leave this open as a reminder.

**Comment by luoliyan** [comment]
I've rewritten the database import code, and definitions should no longer be truncated. However, I've gotten a bit carried away and begun a full rewrite of the code that interfaces with the database, which has broken a lot of tests.

Long story short, this is fixed locally, but you'll have to wait until the end of the week before I push the changes to GitHub. I'll close this now.
