### ISSUE TITLE
Generated fields should re-populate upon editing of Hanzi field

### ISSUE THREAD

**Issue by grabblies** [luoliyan/chinese-support-redux#67]
# User story
I frequently combine vocabulary with example sentences. I first enter the vocabulary in the Hanzi box and tab to generate the pinyin and definition. Then I return to the Hanzi box and add an example sentence from the web. As it stands, these edits will not result in a re-generation of the pinyin or other fields. 

# Requested fix
If the content of the Hanzi box is edited, at least some of the generated fields should be updated, especially pinyin/colors/pronunciation.

**Comment by p2635** [comment]
Sorry I don't quite understand this one. Do you mean the following:

1. Enter a word in Hanzi then get your pinyin/definition, etc.
2. Enter an example sentence in Hanzi and you expect the above fields to be overwritten in step 1?

I think the reason it's currently set this way is so you don't accidentally overwrite your data.

**Comment by grabblies** [comment]
Yes, with the exception of the definition. If I add more Chinese characters
to the first field, then more pinyin gets generated.

**Comment by p2635** [comment]
I see, so you basically want all fields to be updated bar one (definition). The way it currently works is it updates all Chinese related fields so if we start adding exceptions for a select few fields, this could get tricky because everyone has different use cases.

For example for me, I wouldn't want any of my fields changed if they got stuff in it already, what if I accidentally add/remove a character in Hanzi?  I gotta go back and clean it up and all the other fields. I don't know how we would solve this one since we would need to somehow cover every situation. Maybe something to ponder on later.

I guess the workaround for you right now is to just manually clear those fields (pinyin etc) that you want generated. Then when you go back to Hanzi with your sentence and press tab, it should regenerate. If you got a large amount of notes to update, maybe you can just use the bulk edit anki addon to empty out the fields all at once then regenerate them again.

**Comment by luoliyan** [comment]
If someone wants to propose what the behaviour *should* be, I'm happy to
look at it. I've mostly just inherited the behaviour put in place by the
original author. I haven't made a lot of high-level design decisions myself.

Currently (and I'm going by memory because I've been away for a while)
there are a few different rules depending on which edit box loses focus.
Changing the Pinyin, for example, should update the Pinyin ruby field.
Changing the Hanzi field should update everything, but I understand this
has been a bit hit and miss (not an easy problem to fix, but I'm working on
it).

I don't feel strongly about this. Majority opinion will likely prevail here.

**Comment by grabblies** [comment]
@p2635 , updating all fields based on changes in the character field is also good, provided that existing results are not deleted if no result is returned. That way when an example sentence is returned, the pinyin will be generated but the definition won't be changed (due to the fact that it's very unlikely that the Chinese dictionary contains an entry for the entire word + the example sentence). 

Would one of you be willing to direct me to the part of the code where this is controlled, so I can potentially get it working on my own to see if the behavior is ideal?

**Comment by luoliyan** [comment]
Some of the fields are update, while some aren't, which I'm inclined to treat as a bug.

All of the relevant code should be in `behavior.py`. It's a large file, but the logic is pretty straightforward. You just need to read from the bottom, starting with the `update_fields` function.

**Comment by joeminicucci** [comment]
Closing in favor of duplicate issue tracking #137
