### ISSUE TITLE
Sound doesn't fit for some characters

### ISSUE THREAD

**Issue by 3ter** [luoliyan/chinese-support-redux#7]
Hi there,

### Synopsis
As one character may have multiple pronunciations there are cases where the sound doesn't match the reading.

### Steps to reproduce
- Put 分享 in the field "Hanzi"
- Press TAB

### Observed behavior
- The reading is populated with "bì jìng"
- The sound is "fēn xiǎng"

### Expected behavior
- The reading is populated with "fēn xiǎng" as is the sound.

Regards,
3ter

**Comment by luoliyan** [comment]
This needs work. It's on the to-do list.

**Comment by matt-snider** [comment]
Is this the same issue as in #9? I'm seeing this for **薄 báo** being pronounced with the alternate **bó**. 

In cases of ambiguity, one idea would be for the user to specify the reading (e.g. _báo_ or _bao2_)

**Comment by rpetersnil** [comment]
I am still seeing this issue, on the released binary in Anki (latest update - 2019.01.17?). Specifically I am seeing it with the characters 什 （shi2 instead of shen2) and 誰（shui2 instead of shei2). Let me know if you need more info.

**Comment by luoliyan** [comment]
I haven't forgotten about this. There's just a lot of cleanup required at lower levels of the system and that's been my focus. (Without reliable database entries, transcription won't be reliable. Without reliable segmentation, transcription won't be reliable.)

I'll be adding these examples as unit tests, and I'll close this issue when they pass.

**Comment by luoliyan** [comment]
I think there are a few different issues here. The 分享 issue seems to be because the add-on -- correctly -- gets the transcription by looking up the whole word, but it selects the wrong database entry for whatever reason. I'll try to fix that first and see if some of the other problems miraculously resolve.

**Comment by luoliyan** [comment]
Okay, I've fixed that particular example, but I'm a bit fearful that I've introduced other issues in the process.

The problem was that it was taking simplified Chinese 分享 and searching the database for matching simplified _or traditional_. There's a silly entry in the database that I think comes from HanDeDICT that appears to have the wrong word in the traditional field.

Rather than fix HanDeDICT, I've forced the addon to search by simplified when the transcription is Pinyin, and by traditional when it's Bopomofo or Jyutping. If that ruins anyone's life, let me know.
