### ISSUE TITLE
Reading field only filled with pinyin, not zhuyin

### ISSUE THREAD

**Issue by onaphta** [luoliyan/chinese-support-redux#87]
In 0.11.5, with bopomofo chosen as the primary transcription method, pinyin transcription keeps appearing in the "reading" field, no bopomofo unless I specifically create a "bopomofo" field. This didn't happen before.

**Comment by DanGould** [comment]
I can duplicate this.

**Comment by luoliyan** [comment]
Sadly, this is related to the changes made to fix the transcription issues.
It may get fixed in the future, but for now the menu option is not honoured.

I'll need to make a decision as to whether having that option even makes
sense. I'm open to arguments that it's useful, but it adds a lot of
complexity to the back-end and has made bugs harder to fix.

**Comment by onaphta** [comment]
Well, one of the reasons that would make it useful is that right now, the ruby only shows the pinyin, not the zhuyin. 
I found a workaround, which is to replace the "Reading field" with "Bopomofo" and then delete the "pinyin" field, in which case the ruby field will contain zhuyin. But in this case I don't get pinyin at all and I would have to manually edit all my card types.

**Comment by luoliyan** [comment]
But doesn't it show the right thing if you have a Ruby (Zhuyin) field?

**Comment by onaphta** [comment]
You are right, I didn't know we could configure a Ruby (Zhuyin) field.

**Comment by luoliyan** [comment]
That's a fault of my poor documentation, but [config.json](https://github.com/luoliyan/chinese-support-redux/blob/master/chinese/config.json) will always have the complete list of valid field names.
