### ISSUE TITLE
"meaning" field not auto-filling

### ISSUE THREAD

**Issue by chibiauerbach** [luoliyan/chinese-support-redux#96]
**Describe the bug**
"meaning" field not auto-filling for Chinese (Basic) note type. (Sound, pinyin, etc all auto-filling)

**Expected behavior**
Meaning field should auto-fill (it did before I updated to most recent Anki and had to redownload this add-on)

Specs:
 - OS: iOS
 - Anki Version 2.1.15
- Chinese Support Version Redux 0.11.5

**Comment by luoliyan** [comment]
Rename the field to "English" and you should be good to go. A complete list of valid field names is here: https://github.com/luoliyan/chinese-support-redux/blob/master/chinese/config.json

**Comment by raisx13** [comment]
Describe the bug
"meaning" field not auto-filling for Chinese (Basic) note type. (Sound, pinyin, etc all auto-filling)

Expected behavior
Meaning field should auto-fill (it did before I updated to most recent Anki and had to redownload this add-on). There should be "Dictionary" which I can choose the language. 

I have tried to change my configuration adding the fields you said according to the previous answers but it doesn't work either way. Can you be more specific about how to solve this problem?
Specs:
Windows 10 pro
Anki Version 2.1.15
Chinese Support Version Redux 0.11.5

**Comment by chibiauerbach** [comment]
I am also experiencing new problems where the meaning field now works, and all the fields autofill, until suddenly they just stop autofilling completely and i have to close the "Add" box or restart anki to get them to refill again.
